feat: support link variants
prismicio/prismic-client pull request #368
Opened 2024-12-17 02:48 UTC by angeloashmore

**Resolves**: #365

### Description

This PR re-implements #365 based on ##367.

### Checklist

- [ ] A comprehensive Linear ticket, providing sufficient context and details to facilitate the review of the PR, is linked to the PR.
- [x] If my changes require tests, I added them.
- [ ] If my changes affect backward compatibility, it has been discussed.
- [ ] If my changes require an update to the CONTRIBUTING.md guide, I updated it.

### Preview

### How to QA [^1]

[^1]:
	Please use these labels when submitting a review:
	:question: #ask:&ensp;Ask a question.
	:bulb: #idea:&ensp;Suggest an idea.
	:warning: #issue:&ensp;Strongly suggest a change.
	:tada: #nice:&ensp;Share a compliment.

2024-12-17 15:20 UTC, dani-mp approved these changes

2024-12-17 16:41 UTC, xrutayisire requested changes
⚠️ It's missing the update of `getOptionalLinkProperties` no?

2024-12-17 22:46 UTC, angeloashmore commented
@xrutayisire I added a comment above `OptionalLinkProperties` to remind devs to update `getOptionalLinkProperties`: https://github.com/prismicio/prismic-client/blob/8217ae665e193459c77c735f6e046c1323176414/src/types/value/link.ts#L88-L89

2024-12-23 10:35 UTC, xrutayisire approved these changes
LGTM!

2024-12-23 13:51 UTC, merged